train:
  dataset:
    name: dummy
    path: data/TinyGenImage
  opt:
    earlystop_epoch: 5
    data_aug: False
    optim: adam
    new_optim: True
    loss_freq: 400
    save_latest_freq: 2000
    save_epoch_freq: 20
    continue_train: False
    epoch_count: 10
    last_epoch: -1
    train_split: train
    val_split: val
    niter: 10000
    beta1: 0.9
    lr: 0.0001
    batch_size: 32