name: ResNet_noPretrain_fourier
isTrain: True
gpu_ids: [0]
checkpoints_dir: output/ResNet_noPretrain_fourier/checkpoints
output_dir: output/ResNet_noPretrain_fourier/

fourier: False
train:
  dataset:
    name: GenImage
    path: data/GenImage
    # leave_out: 1
  earlystop_epoch: 5
  data_aug: False
  optim: adam
  new_optim: True
  loss_freq: 1
  save_latest_freq: 2000
  save_epoch_freq: 20
  save_img_freq: 10
  n_img_to_log: 5
  continue_train: False
  epoch_count: 10
  epoch_size: 10000
  val_size: 1000
  last_epoch: -1
  train_split: train
  val_split: val
  niter: 10000
  beta1: 0.9
  lr: 0.0001
  lr_policy: step
  lr_decay_epoch: 10000
  batch_size: 32
  num_workers: 10